version: '3.2'

services:
  backend:
    image: thecodingmachine/php:8.0-v4-cli
    container_name: backend
    environment:
      STARTUP_COMMAND_1: composer install
    volumes:
      - "./backend/:/app"
    working_dir: /app
    command: "php -S 0.0.0.0:80 -t public public/index.php"
    ports:
      - "80:80"
    links:
      - redis
    depends_on:
      - redis
    networks:
      - challenge

  frontend:
    image: "node:12"
    container_name: frontend
    volumes:
      - "./frontend/:/home/node/app"
    expose:
      - "8080"
    command: bash -c "
      npm ci && npm run serve
      "
    working_dir: /home/node/app
    ports:
      - "8080:8080"
    links:
      - backend
    depends_on:
      - backend
    networks:
      - challenge

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    networks:
      - challenge

networks:
  challenge:
    driver: bridge

volumes:
  redis:

